export function applyAllScript(): string {
  return `#!/usr/bin/env bash
# Repo Shield — Pro: apply the protection pack to every public repo of a
# GitHub user or org in one pass. Requires the gh CLI and gh auth login.
# Usage: ./apply-all.sh <owner> <license> <holder> <year-of-first-copyright>
#
# Verification is left to the repo's own Repo Shield workflow once committed.
set -euo pipefail

OWNER="\${1:?usage: apply-all.sh <owner> <license> <holder> <year>}"
LICENSE="\${2?missing license (mit|isc|unlicense|apache-2.0|gpl-3.0)}"
HOLDER="\${3?missing holder name}"
YEAR="\${4:-$(date +%Y)}"

cd "\$(dirname "\$0")"
PACK="\$(pwd)/repo-shield-pack"   # files generated by the Repo Shield app
WORK="\$(mktemp -d)"
trap 'rm -rf "\$WORK"' EXIT

ensure_pack() {
  for f in LICENSE NOTICE AI_TRAINING_POLICY.md repo-shield.yml shield-check.mjs; do
    if [ ! -f "\$PACK/\$f" ]; then
      echo "Missing \$PACK/\$f — generate the pack from the Repo Shield app first." >&2
      exit 1
    fi
  done
}
ensure_pack

repos=$(gh repo list "\$OWNER" --limit 500 --json name --jq '.[].name')
count=0
while IFS= read -r repo; do
  [ -z "\$repo" ] && continue
  # skip forks
  if ! gh api "repos/\$OWNER/\$repo" --jq '.fork'; then
    echo ">> \$repo"
    gh repo clone "\$OWNER/\$repo" "\$WORK/\$repo" -- --quiet
    cd "\$WORK/\$repo"
    cp "\$PACK/LICENSE" "\$PACK/NOTICE" "\$PACK/AI_TRAINING_POLICY.md" .
    mkdir -p .github/workflows scripts
    cp "\$PACK/repo-shield.yml" .github/workflows/
    cp "\$PACK/shield-check.mjs" scripts/
    git add LICENSE NOTICE AI_TRAINING_POLICY.md .github/workflows/repo-shield.yml scripts/shield-check.mjs
    if git diff --cached --quiet; then
      echo "   (no changes)"
    else
      git commit -q -m "Protect repo: license, AI-training notice, Repo Shield workflow"
      git push -q origin HEAD
    fi
    cd "\$WORK"
    count=$((count + 1))
  fi
done <<< "\$repos"

echo "Protected \$count repos for \$OWNER."
echo "Verify each repo's Actions > Repo Shield run turns green."
`;
}

export function applyAllNote(): string {
  return `# Pro: apply to all your repos
1. Save apply-all.sh, run: chmod +x apply-all.sh
2. Run: ./apply-all.sh <owner> <license> <holder> <year>
3. Requires gh auth login and write access to each repo.
4. Each repo gets its own Repo Shield workflow (weekly monitoring).

The script skips forks and refuses to touch repos it did not change.
It modifies ONLY these files: LICENSE, NOTICE, AI_TRAINING_POLICY.md,
.github/workflows/repo-shield.yml, scripts/shield-check.mjs
`;
}