#!/usr/bin/env python3
"""Fetch the five Repo Shield license texts from the official SPDX registry.

Source of truth: https://github.com/spdx/license-list-data (detail JSON files).
Emits cli/lib/spdx.ts (TS module with canonical text + metadata).

Usage:
    python3 scripts/fetch_spdx_licenses.py           # network fetch + emit
    python3 scripts/fetch_spdx_licenses.py --check   # verify existing file only
"""
import json
import sys
import urllib.request
from pathlib import Path

BASE = "https://raw.githubusercontent.com/spdx/license-list-data/main/json/details"

# internal id  -> (SPDX licenseId, canonical detail URL page)
IDS = {
    "mit": "MIT",
    "isc": "ISC",
    "unlicense": "Unlicense",
    "apache-2.0": "Apache-2.0",
    "gpl-3.0": "GPL-3.0-only",
}

OUT = Path(__file__).resolve().parent.parent / "cli" / "lib" / "spdx.ts"


def fetch(id_: str) -> dict:
    url = f"{BASE}/{id_}.json"
    with urllib.request.urlopen(url, timeout=30) as r:
        if r.status != 200:
            raise RuntimeError(f"GET {url} -> HTTP {r.status}")
        return json.loads(r.read().decode("utf-8"))


def build() -> list[dict]:
    rows = []
    for internal, spdx_id in IDS.items():
        d = fetch(spdx_id)
        text = d.get("licenseText", "")
        if not text.strip():
            raise RuntimeError(f"{spdx_id}: empty licenseText")
        if d.get("isDeprecatedLicenseId"):
            raise RuntimeError(f"{spdx_id}: is deprecated by SPDX — refusing to embed")
        if not d.get("isOsiApproved"):
            raise RuntimeError(f"{spdx_id}: not OSI-approved — refusing to embed")
        rows.append(
            {
                "id": internal,
                "spdxId": d["licenseId"],
                "name": d["name"],
                "osiApproved": bool(d["isOsiApproved"]),
                "deprecated": bool(d["isDeprecatedLicenseId"]),
                "canonicalUrl": d.get("detailsUrl", f"https://spdx.org/licenses/{spdx_id}.html"),
                "text": text,
            }
        )
    return rows


def emit(rows: list[dict]) -> str:
    lines = [
        "// This file is generated by scripts/fetch_spdx_licenses.py from the",
        "// official SPDX license registry (license-list-data). DO NOT EDIT BY HAND.",
        "// Regenerate: python3 scripts/fetch_spdx_licenses.py",
        "",
        "export interface SpdxLicense {",
        "  id: \"mit\" | \"isc\" | \"unlicense\" | \"apache-2.0\" | \"gpl-3.0\";",
        "  spdxId: string;",
        "  name: string;",
        "  osiApproved: boolean;",
        "  deprecated: boolean;",
        "  canonicalUrl: string;",
        "  text: string;",
        "}",
        "",
        f"export const SPDX_LICENSES: SpdxLicense[] = {json.dumps(rows, indent=2, ensure_ascii=False)};",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    if "--check" in sys.argv:
        if not OUT.exists():
            print(f"missing: {OUT}")
            return 1
        data = json.loads(OUT.read_text().split("= ", 1)[1].rstrip().rstrip(";"))
        print(f"ok: {OUT} ({len(data)} licenses)")
        return 0
    rows = build()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(emit(rows), encoding="utf-8")
    print(f"wrote {OUT}")
    for row in rows:
        print(f"  {row['id']:12} {row['spdxId']:16} osi={row['osiApproved']}  text={len(row['text'])}B  {row['canonicalUrl']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())